apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservis-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EmreYsrc/microservices-demo.git
    targetRevision: main
    path: helm-chart
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

